"""
Render template plugin - renders campaign template with variables
"""
from typing import Dict, Any, Optional, List
from ..base import BasePlugin
from shared.template_render import render_sandboxed
from shared.database import Template
import logging

logger = logging.getLogger(__name__)

class RenderTemplatePlugin(BasePlugin):
    """
    Plugin for rendering HTML templates with variable interpolation and Jinja2 templating.
    
    Renders templates from campaign configuration, custom HTML, or context variables.
    Supports both simple variable interpolation ({{variable}}) and full Jinja2 templating
    syntax for complex logic, loops, and conditionals.
    
    Use cases:
    - Render dynamic HTML pages with user-specific data
    - Generate personalized email content
    - Create multi-step forms with conditional sections
    - Build dynamic landing pages based on context
    - Transform template variables into final HTML
    
    Example: Render campaign template with {{target.name}} and {{target.email}},
    or use Jinja2 {% if %} blocks for conditional content.
    """
    
    @property
    def plugin_type(self) -> str:
        return "render_template"
    
    @property
    def display_name(self) -> str:
        return "Render Template"
    
    @property
    def description(self) -> str:
        return "Render HTML templates with variable interpolation and Jinja2 syntax. Supports campaign templates, custom HTML, or templates from context variables. Use to generate dynamic pages, personalized content, and conditional HTML based on workflow context."
    
    @property
    def plugin_category(self) -> str:
        return "template"
    
    @property
    def config_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "template_source": {
                    "type": "string",
                    "title": "Template Source",
                    "enum": [
                        {
                            "value": "campaign",
                            "label": "Campaign Template",
                            "description": "Use the campaign's configured template HTML. Best for standard campaign pages that use the main template."
                        },
                        {
                            "value": "custom",
                            "label": "Custom HTML",
                            "description": "Enter HTML template directly in the configuration. Best for one-off templates or dynamic content generation."
                        },
                        {
                            "value": "variable",
                            "label": "From Context Variable",
                            "description": "Read template HTML from a context variable. Best for templates generated by previous plugins or stored in workflow variables."
                        },
                        {
                            "value": "library",
                            "label": "Template from library",
                            "description": "Use a template from the Templates menu. Select below. Best for reusing saved templates across workflows."
                        }
                    ],
                    "description": "Where to get the template HTML from",
                    "help": "Choose the source of your template. Campaign template uses the campaign's main template, custom lets you write HTML directly, variable reads from a context variable, and library lets you pick a template from the Templates menu.",
                    "default": "campaign"
                },
                "custom_template": {
                    "type": "string",
                    "title": "Custom HTML Template",
                    "description": "HTML template with variable interpolation",
                    "help": "Enter your HTML template here. Supports variable interpolation with {{variable}} syntax and full Jinja2 templating ({% if %}, {% for %}, etc.). Example: <h1>Hello {{target.name}}</h1><p>Your email: {{target.email}}</p>{% if target.verified %}<span>Verified</span>{% endif %}",
                    "placeholder": "<html><body><h1>{{target.name}}</h1></body></html>"
                },
                "template_variable": {
                    "type": "string",
                    "title": "Template Variable Name",
                    "description": "Context variable name containing the template HTML",
                    "help": "Name of the context variable that contains the template HTML. Can be set by a previous plugin or workflow variable. The variable should contain HTML with variable interpolation syntax.",
                    "placeholder": "template, email_template, dynamic_html",
                    "default": "template"
                },
                "template_id": {
                    "type": "integer",
                    "title": "Template",
                    "description": "Template from the template library",
                    "help": "Template from the template library. Used when Template source is 'Template from library'.",
                    "placeholder": "Select a template",
                    "x-optionsSource": "templates"
                },
                "output_variable": {
                    "type": "string",
                    "title": "Output Variable Name",
                    "description": "Context variable name to store the rendered HTML",
                    "help": "Name of the context variable where the rendered HTML will be stored. This can be used by subsequent plugins (e.g., SMTP sender, redirect with HTML response). Also sets '_response_html' for HTTP response handling.",
                    "placeholder": "html, rendered_content, email_body",
                    "default": "html"
                }
            },
            "required": []
        }
    
    def execute(self, context: Dict[str, Any], config: Dict[str, Any]) -> Dict[str, Any]:
        """Execute template rendering"""
        try:
            template_source = config.get('template_source', 'campaign')
            output_var = config.get('output_variable', 'html')
            
            # Get template HTML
            if template_source == 'campaign':
                template_html = context.get('campaign', {}).get('template_html', '')
            elif template_source == 'custom':
                template_html = config.get('custom_template', '')
            elif template_source == 'variable':
                var_name = config.get('template_variable', 'template')
                template_html = context.get(var_name, '')
            elif template_source == 'library':
                template_id = config.get('template_id')
                template_html = ''
                if template_id:
                    template = Template.query.get(template_id)
                    if template:
                        template_html = template.template_html or ''
                    else:
                        logger.warning(f"Template {template_id} not found")
            else:
                raise ValueError(f"Unknown template_source: {template_source}")
            
            if not template_html:
                logger.warning("No template HTML found")
                fallback = (
                    "<html><body><h1>No template available</h1>"
                    "<p>No campaign template set. Use Template from library, Custom HTML, or From context variable "
                    "in the Render Template node for workflow-defined campaigns.</p></body></html>"
                )
                context[output_var] = fallback
                context['_response_html'] = fallback
                return context
            
            # Inject media helper functions for Jinja2 templates.
            #
            # qr_code() / text_image() return URLs the browser fetches separately
            # (cached server-side after first hit). Use these for shared/cacheable
            # images and to keep the rendered HTML small.
            #
            # qr_code_inline() / text_image_inline() / logo_inline() return
            # data:image/png;base64,... URIs baked directly into the HTML.
            # Use these when you want the image generated server-side at render
            # time with no extra browser request to your phishing host.
            from shared.media_urls import get_phishing_base_url, build_qr_url, build_text_image_url
            from shared.mms_card_html import (
                qr_code_data_uri, text_image_data_uri, logo_data_uri,
            )
            _base_url = get_phishing_base_url(context)

            def qr_code(data, box_size=10, border=4, fill_color='#000000',
                        bg_color='#FFFFFF', error_correction='M'):
                return build_qr_url(_base_url, str(data), box_size=box_size,
                                    border=border, fill_color=fill_color,
                                    bg_color=bg_color, error_correction=error_correction)

            def text_image(text, font_size=64, width=600, height=200,
                           bg_color='#FFFFFF', text_color='#000000'):
                return build_text_image_url(_base_url, str(text), font_size=font_size,
                                            width=width, height=height,
                                            bg_color=bg_color, text_color=text_color)

            context['qr_code'] = qr_code
            context['text_image'] = text_image
            context['qr_code_inline'] = qr_code_data_uri
            context['text_image_inline'] = text_image_data_uri
            context['logo_inline'] = logo_data_uri

            # Render with sandboxed Jinja2 (autoescape on). Variable values are
            # never re-parsed as Jinja, closing the SSTI vector.
            try:
                rendered_html = render_sandboxed(template_html, context)
            except Exception as e:
                logger.error(f"Template rendering error: {e}")
                rendered_html = (
                    "<html><body><h1>Template error</h1>"
                    "<p>The page template could not be rendered.</p></body></html>"
                )

            # Clean up non-serializable helpers from context
            context.pop('qr_code', None)
            context.pop('text_image', None)
            context.pop('qr_code_inline', None)
            context.pop('text_image_inline', None)
            context.pop('logo_inline', None)

            # Store in context
            context[output_var] = rendered_html
            context['_response_html'] = rendered_html
            # So /assets/ can serve from this template when workflow uses "Template from library"
            if template_source == 'library' and config.get('template_id'):
                context['_rendered_template_id'] = config['template_id']

            logger.debug(f"Template rendered and stored in '{output_var}'")
            return context
            
        except Exception as e:
            logger.error(f"Template rendering failed: {e}")
            return self.on_error(e, context, config)
    
    def validate_config(self, config: Dict[str, Any]) -> Optional[List[str]]:
        """Validate template configuration"""
        errors = []
        
        template_source = config.get('template_source', 'campaign')
        
        if template_source == 'custom' and not config.get('custom_template'):
            errors.append("custom_template is required when template_source is 'custom'")
        
        if template_source == 'variable' and not config.get('template_variable'):
            errors.append("template_variable is required when template_source is 'variable'")
        
        if template_source == 'library':
            template_id = config.get('template_id')
            if not template_id:
                errors.append("template_id is required when template_source is 'library'")
            elif not Template.query.get(template_id):
                errors.append("Selected template not found")
        
        return errors if errors else None




